language: python

python:
- 3.5
- 3.6
- 3.6-dev
- 3.7
- 3.7-dev

# required for python >= 3.7
dist: xenial

install:
- pip install pipenv
- pipenv sync --dev

script:
- pipenv run pylint freesurfer_volume_reader
- pipenv run pytest
